# These are supported funding model platforms

github: [melchisedech333] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: xor-neural-network # Replace with a single Open Collective username
custom: https://github.com/sponsors/melchisedech333 # Replace with a single custom sponsorship URL


